pre:
  - command: shell.exec
    params:
      working_dir: "giza"
      script: |
        virutalenv ~/venv-giza
        source ~/venv-giza/bin/activate

        pip install .

tasks:
  - name: "unit-tests"
    commands: shell.exec
    params:
      working_dir: "giza"
      script: |
        source ~/venv-giza/bin/activate
        make -k test
  - name: "mms-docs-minimal-test"
    commands: shell.exec
    params:
      script: |
        source ~/venv-giza/bin/activate
        giza test --project mms-docs --operation minimal
  - name: "manual-minimal-test"
    commands: shell.exec
    params:
      script: |
        source ~/venv-giza/bin/activate
        giza test --project mongodb-manual --operation minimal
  - name: "primer-minimal-test"
    commands: shell.exec
    params:
      script: |
        source ~/venv-giza/bin/activate
        giza test --project mongodb-primer --operation minimal
  - name: "ecosystem-minimal-test"
    commands: shell.exec
    params:
      script: |
        source ~/venv-giza/bin/activate
        giza test --project docs-ecosystem --operation minimal
  - name: "training-minimal-test"
    commands: shell.exec
    params:
      script: |
        source ~/venv-giza/bin/activate
        giza test --project docs-training --operation minimal
  - name: "mongodb-www-about-minimal-test"
    commands: shell.exec
    params:
      script: |
        source ~/venv-giza/bin/activate
        giza test --project www-about --operation minimal


buildvariants:
  - name: ubuntu1404-release
    display_name: "Ubuntu 14.04"
    run_on:
      - ubuntu1404-test
    tasks:
      - name: "unit-tests"
      - name: "mms-docs-minimal-test"
      - name: "manual-minimal-test"
      - name: "primer-minimal-test"
      - name: "ecosystem-minimal-test"
      - name: "training-minimal-test"
      - name: "mongodb-www-about-minimal-test"
