pre:
  - command: shell.exec
    params:
      working_dir: "giza"
      script: |
        virtualenv ~/venv
        ${venv}/pip install .
        ${venv}/pip install pep8 pyflakes nosetests


tasks:
  - name: "small-tests"
    commands: shell.exec
    params:
      script: |
        make -C giza/ -k test

        ${venv}/giza test --project www-about --operation minimal
        ${venv}/giza test --project docs-ecosystem --operation minimal
  - name: "mms-docs-minimal-test"
    commands: shell.exec
    params:
      script: |
        ${venv}/giza test --project mms-docs --operation minimal
  - name: "manual-minimal-test"
    commands: shell.exec
    params:
      script: |
        ${venv}/giza test --project mongodb-manual --operation minimal
  - name: "primer-minimal-test"
    commands: shell.exec
    params:
      script: |
        ${venv}/giza test --project mongodb-primer --operation minimal
  - name: "training-minimal-test"
    commands: shell.exec
    params:
      script: |
        ${venv}/giza test --project docs-training --operation minimal


buildvariants:
  - name: ubuntu1404-release
    display_name: "Ubuntu 14.04"
    run_on:
      - ubuntu1404-test
    expansions:
      venv: "~/venv/bin"
    tasks:
      - name: "small-tests"
      - name: "mms-docs-minimal-test"
      - name: "manual-minimal-test"
      - name: "primer-minimal-test"
      - name: "training-minimal-test"
