pre:
  - command: git.get_project
    params:
      directory: "docs-tools"
  - command: git.apply_patch
    params:
      directory: "docs-tools"
  - command: shell.exec
    params:
      working_dir: "docs-tools/giza"
      script: |
        virtualenv ~/venv
        ${venv}/pip install .
        ${venv}/pip install pep8 pyflakes  # nose


tasks:
  - name: "small-tests"
    commands:
      - command: shell.exec
        params:
          working_dir: "docs-tools/giza"
          script: |
            # ${venv}/nosetests ./test
            ${venv}/pyflakes giza
            ${venv}/pep8 --max-line-length=100 giza
      - command: shell.exec
        params:
          working_dir: "docs-tools"
          script: |
            export PATH=${venv}:$PATH

            ${venv}/giza test --project www-about --operation minimal --giza-path ${venv}/giza
            ${venv}/giza test --project docs-ecosystem --operation minimal --giza-path ${venv}/giza
  - name: "mms-docs-minimal-test"
    commands:
      - command: shell.exec
        params:
          working_dir: "docs-tools"
          script: |
            export PATH=${venv}:$PATH

            ${venv}/giza test --project mms-docs --operation minimal --giza-path ${venv}/giza
  - name: "manual-minimal-test"
    commands:
      - command: shell.exec
        params:
          working_dir: "docs-tools"
          script: |
            export PATH=${venv}:$PATH

            ${venv}/giza test --project mongodb-manual --operation minimal --giza-path ${venv}/giza
  - name: "primer-minimal-test"
    commands:
      - command: shell.exec
        params:
          working_dir: "docs-tools"
          script: |
            export PATH=${venv}:$PATH

            ${venv}/giza test --project mongodb-primer --operation minimal --giza-path ${venv}/giza
  - name: "training-minimal-test"  # disabled because of access
    commands:
      - command: shell.exec
        params:
          working_dir: "docs-tools"
          script: |
            export PATH=${venv}:$PATH

            ${venv}/giza test --project docs-training --operation minimal --giza-path ${venv}/giza


buildvariants:
  - name: ubuntu1404-release
    display_name: "Ubuntu 14.04"
    run_on:
      - ubuntu1404-test
    expansions:
      venv: "~/venv/bin"
    tasks:
      - name: "small-tests"
      - name: "mms-docs-minimal-test"
      - name: "manual-minimal-test"
      - name: "primer-minimal-test"
      # - name: "training-minimal-test"
