git:
  remote:
    upstream: 'mongodb/docs-bi-connector'
    tools: 'mongodb/docs-tools'
project:
  name: 'bi-connector'
  tag: 'bi-connector'
  url: 'https://docs.mongodb.com/bi-connector'
  title: "MongoDB Regression Testing"
  branched: true
system:
  tools:
    ref: HEAD
    pinned: false
  make:
    generated:
      - 'sphinx'
      - 'meta'
      - 'push'
      - 'integration'
    static:
      - 'makefile.compatibility'
      - 'makefile.clean'
  files:
    - 'pdfs.yaml'
    - 'intersphinx.yaml'
    - 'push.yaml'
    - 'integration.yaml'
    - 'sphinx_local.yaml'
    - htaccess: ['htaccess.yaml']
version:
  release: '2.3'
  branch: 'master'
paths:
  output: 'build'
  source: 'source'
  includes: 'source/includes'
  images: 'source/images'
  tools: 'bin'
  buildsystem: 'build/docs-tools'
  builddata: 'config'
...
